In [4]:
import sys
print('Python: {}'.format(sys.version))
import scipy
print('Python: {}'.format(scipy.version))
import numpy
print('Python: {}'.format(numpy.version))
import matplotlib
print('Python: {}'.format(matplotlib))
import pandas
print('Python: {}'.format(pandas))
import sklearn
print('Python: {}'.format(sklearn))


Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Python: <module 'scipy.version' from 'C:\\Users\\User\\surfinteg\\Lib\\site-packages\\scipy\\version.py'>
Python: <module 'numpy.version' from 'C:\\Users\\User\\surfinteg\\Lib\\site-packages\\numpy\\version.py'>
Python: <module 'matplotlib' from 'C:\\Users\\User\\surfinteg\\Lib\\site-packages\\matplotlib\\__init__.py'>
Python: <module 'pandas' from 'C:\\Users\\User\\surfinteg\\Lib\\site-packages\\pandas\\__init__.py'>
Python: <module 'sklearn' from 'C:\\Users\\User\\surfinteg\\Lib\\site-packages\\sklearn\\__init__.py'>


In [1]:
from pandas import read_excel
from pandas.plotting import scatter_matrix
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [29]:
# Load dataset FOR TRAINING AND TESTING tanpa 3 bola
from pandas import read_excel

url = "D:\\Nazla_Innaya\\S2\\Kuliah\\Sem3\\Studi_Mandiri_II_FI6092\\1_5_bola\\tanpabola3.xlsx"
names = ['lam_max1', 'csc_max1', 'lam_min', 'csc_min','lam_fwhm1','c_mid','lam_max2','csc_max2','lam_fwhm2','fwhm','posisi1','posisi2','posisi3','posisi4','posisi5','arah_k','arah_E','sb_putar','sudut1','sudut2','ket'] 
dataset = read_excel(url, names=names, header=None)

#print(dataset.head(10))

In [30]:
import sklearn

print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 1.4.2.


In [31]:
import matplotlib.pyplot as plt

In [74]:
# Load dataset for validation 
from pandas import read_excel

url = "D:\\Nazla_Innaya\\S2\\Kuliah\\Sem3\\Studi_Mandiri_II_FI6092\\1_5_bola\\3bola.xlsx"
names = ['lam_max1', 'csc_max1', 'lam_min', 'csc_min','lam_fwhm1','c_mid','lam_max2','csc_max2','lam_fwhm2','fwhm','posisi1','posisi2','posisi3','posisi4','posisi5','arah_k','arah_E','sb_putar','sudut1','sudut2','ket'] 
dataset2 = read_excel(url, names=names, header=None)

array2 = dataset2
#print(array[:5])
#print()

X2 = array2.iloc[:,0:4].values
#print(X[:5])
#print()

y2 = array2.iloc[:,4].values
#print(y[:5])

Z = array2.iloc[:,10:20].values
print(Z)

[[0 0 1 ... 1 0 0]
 [0 0 1 ... 1 1 5]
 [0 0 1 ... 1 3 0]
 ...
 [1 1 1 ... 3 6 0]
 [1 1 1 ... 3 7 5]
 [1 1 1 ... 3 9 0]]


In [33]:
# Split-out validation dataset
array = dataset
X = array.iloc[:,0:10].values
y = array.iloc[:,20].values
X_train, X_validation, Y_train, Y_validation = train_test_split(
    X, y, test_size=0.50
    #random_state=1
)

print(len(Y_train))
print(len(Y_validation))
print(len(Y_validation)/(len(Y_train) + len(Y_validation)))
                                                                

535
536
0.5004668534080299


In [34]:
# Spot check algorithms
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))

#evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = StratifiedKFold(n_splits=2, random_state=1, shuffle=True)
    cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))
    


LR: 0.689712 (0.004318)
LDA: 0.803797 (0.031409)
KNN: 0.871038 (0.005366)
CART: 0.891616 (0.014751)
NB: 0.581286 (0.011998)
SVM: 0.897220 (0.012892)


In [38]:
# Make predictions on validation dataset
modelSVM = SVC(gamma='auto')
modelSVM.fit(X_train, Y_train)
predictions = modelSVM.predict(X_validation)

In [39]:
# Evaluate predictions using SVM
print("accuracy = ",
     accuracy_score(
         Y_validation, predictions))
cf = confusion_matrix(Y_validation, predictions)
print("\nconfusion matrix =\n", cf)

print("\nreport = \n", 
     classification_report(
         Y_validation, predictions))

accuracy =  0.9104477611940298

confusion matrix =
 [[188   0  33]
 [  0  90   6]
 [  5   4 210]]

report = 
               precision    recall  f1-score   support

           0       0.97      0.85      0.91       221
           1       0.96      0.94      0.95        96
           2       0.84      0.96      0.90       219

    accuracy                           0.91       536
   macro avg       0.92      0.92      0.92       536
weighted avg       0.92      0.91      0.91       536



In [40]:
# Make predictions using CART
modelCART = DecisionTreeClassifier()
modelCART.fit(X_train, Y_train)
predictions = modelCART.predict(X_validation)

# Evaluate predictions
print("accurancy = ",
     accuracy_score(
         Y_validation, predictions))
print("\nconfusion matrix =\n",
     confusion_matrix(
         Y_validation, predictions))
print("\nreport = \n", 
     classification_report(
         Y_validation, predictions))

accurancy =  0.8955223880597015

confusion matrix =
 [[195   0  26]
 [  0  92   4]
 [ 26   0 193]]

report = 
               precision    recall  f1-score   support

           0       0.88      0.88      0.88       221
           1       1.00      0.96      0.98        96
           2       0.87      0.88      0.87       219

    accuracy                           0.90       536
   macro avg       0.92      0.91      0.91       536
weighted avg       0.90      0.90      0.90       536



In [41]:
#X = array.iloc[:,0:10].values
#y = array.iloc[:,20].values
X_test1 = array2.iloc[50:71,0:10].values
y_test1 = array2.iloc[50:71:,20].values
X_test2 = array2.iloc[187:201,0:10].values
y_test2 = array2.iloc[187:201:,20].values
X_test3 = array2.iloc[333:347,0:10].values
y_test3 = array2.iloc[333:347:,20].values
X_test4 = array2.iloc[501:519,0:10].values
y_test4 = array2.iloc[501:519:,20].values

predictions = modelSVM.predict(X_test1)
print(predictions)
print(y_test1)

predictions = modelSVM.predict(X_test2)
print(predictions)
print(y_test2)

predictions = modelSVM.predict(X_test3)
print(predictions)
print(y_test3)

predictions = modelSVM.predict(X_test4)
print(predictions)
print(y_test4)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[1 1 2 2 2 2 2 2 2 2 2 2 2 2]
[2 0 0 0 0 0 0 0 0 0 0 0 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2 2 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [75]:
#X = array.iloc[:,0:10].values
#y = array.iloc[:,20].values
X_test1 = array2.iloc[50:71,0:10].values
y_test1 = array2.iloc[50:71:,20].values
z_test1 = array2.iloc[50:71:,10:20].values
X_test2 = array2.iloc[187:208,0:10].values
y_test2 = array2.iloc[187:208:,20].values
z_test2 = array2.iloc[187:208:,10:20].values
X_test3 = array2.iloc[333:354,0:10].values
y_test3 = array2.iloc[333:354:,20].values
z_test3 = array2.iloc[333:354:,10:20].values
X_test4 = array2.iloc[501:522,0:10].values
y_test4 = array2.iloc[501:522:,20].values
z_test4 = array2.iloc[501:522:,10:20].values

predictions = modelCART.predict(X_test1)
print(predictions)
print(y_test1)

predictions = modelCART.predict(X_test2)
print(predictions)
print(y_test2)

predictions = modelCART.predict(X_test3)
print(predictions)
print(y_test3)

predictions = modelCART.predict(X_test4)
print(predictions)
print(y_test4)



[1 1 1 1 1 1 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1]
[0 0 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 2 1]
[1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [76]:
X_tests=np.concatenate((X_test1,X_test2,X_test3,X_test4))
y_tests=np.concatenate((y_test1,y_test2,y_test3,y_test4))
z_tests=np.concatenate((z_test1,z_test2,z_test3,z_test4))
predictionsCART = modelCART.predict(X_tests)
print(predictionsCART)
print(y_tests)

print("accurancy = ",
     accuracy_score(
         y_tests, predictionsCART))
print("\nconfusion matrix =\n",
     confusion_matrix(
         y_tests, predictionsCART))
print("\nreport = \n", 
     classification_report(
         y_tests, predictionsCART))


[1 1 1 1 1 1 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2 0 0 1 1 1 1 1 1 1 1 1 1 2 1 1 2
 1 1 1 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1]
accurancy =  0.5238095238095238

confusion matrix =
 [[19  2  0]
 [ 5 18  8]
 [ 0 25  7]]

report = 
               precision    recall  f1-score   support

           0       0.79      0.90      0.84        21
           1       0.40      0.58      0.47        31
           2       0.47      0.22      0.30        32

    accuracy                           0.52        84
   macro avg       0.55      0.57      0.54        84
weighted avg       0.52      0.52      0.50        84



In [58]:
X_tests=np.concatenate((X_test1,X_test2,X_test3,X_test4))
y_tests=np.concatenate((y_test1,y_test2,y_test3,y_test4))
predictionsSVM = modelSVM.predict(X_tests)
print(predictionsSVM)
print(y_tests)

print("accurancy = ",
     accuracy_score(
         y_tests, predictionsSVM))
print("\nconfusion matrix =\n",
     confusion_matrix(
         y_tests, predictionsSVM))
print("\nreport = \n", 
     classification_report(
         y_tests, predictionsSVM))

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
accurancy =  0.6716417910447762

confusion matrix =
 [[11  0  3]
 [ 0  9 19]
 [ 0  0 25]]

report = 
               precision    recall  f1-score   support

           0       1.00      0.79      0.88        14
           1       1.00      0.32      0.49        28
           2       0.53      1.00      0.69        25

    accuracy                           0.67        67
   macro avg       0.84      0.70      0.69        67
weighted avg       0.83      0.67      0.65        67



## test

In [15]:
url2 = "D:\\Nazla_Innaya\\S2\\Kuliah\\Sem3\\Studi_Mandiri_II_FI6092\\1_5_bola\\tanpabola3.xlsx"
names2 = ['lam_max1', 'csc_max1', 'lam_min', 'csc_min','lam_fwhm1','c_mid','lam_max2','csc_max2','lam_fwhm2','fwhm','posisi1','posisi2','posisi3','posisi4','posisi5','arah_k','arah_E','sb_putar','sudut1','sudut2','ket'] 
dataset2 = read_excel(url2, names=names2, header=None)

array2 = dataset2
print(len (array2))
X_test5 = array2.iloc[151:157,0:10].values
y_test5 = array2.iloc[151:157:,20].values
X_test6 = array2.iloc[11:17,0:10].values
y_test6 = array2.iloc[11:17:,20].values
X_test7 = array2.iloc[291:301,0:10].values
y_test7 = array2.iloc[291:301:,20].values

predictions = model.predict(X_test5)
print(predictions)
print(y_test5)

predictions = model.predict(X_test6)
print(predictions)
print(y_test6)

predictions = model.predict(X_test7)
print(predictions)
print(y_test7)


1071
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 2 0 2 2 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [79]:
print('tests\t svm \t cart \t konf')
for t,s,c,z in zip(y_tests,predictionsSVM,predictionsCART,z_tests) :
    print(t,s,c,z[0:5],z[5:], sep='\t')

tests	 svm 	 cart 	 konf
2	2	1	[0 0 1 1 1]	[3 2 2 1 5]
2	2	1	[0 0 1 1 1]	[3 2 2 3 0]
2	2	1	[0 0 1 1 1]	[3 2 2 4 5]
2	2	1	[0 0 1 1 1]	[3 2 2 6 0]
2	2	1	[0 0 1 1 1]	[3 2 2 7 5]
2	2	1	[0 0 1 1 1]	[3 2 2 9 0]
2	2	2	[0 0 1 1 1]	[3 2 3 0 0]
2	2	1	[0 0 1 1 1]	[3 2 3 1 5]
2	2	1	[0 0 1 1 1]	[3 2 3 3 0]
2	2	1	[0 0 1 1 1]	[3 2 3 4 5]
2	2	2	[0 0 1 1 1]	[3 2 3 6 0]
2	2	2	[0 0 1 1 1]	[3 2 3 7 5]
2	2	2	[0 0 1 1 1]	[3 2 3 9 0]
1	2	2	[0 1 0 1 1]	[1 2 1 0 0]
1	2	2	[0 1 0 1 1]	[1 2 1 1 5]
1	2	2	[0 1 0 1 1]	[1 2 1 3 0]
1	2	2	[0 1 0 1 1]	[1 2 1 4 5]
1	2	2	[0 1 0 1 1]	[1 2 1 6 0]
1	2	2	[0 1 0 1 1]	[1 2 1 7 5]
1	2	2	[0 1 0 1 1]	[1 2 1 9 0]
1	2	2	[0 1 0 1 1]	[1 2 3 0 0]
1	2	0	[0 1 1 0 1]	[3 2 3 7 5]
1	2	0	[0 1 1 0 1]	[3 2 3 9 0]
2	2	1	[0 1 1 1 0]	[1 2 1 0 0]
2	2	1	[0 1 1 1 0]	[1 2 1 1 5]
2	2	1	[0 1 1 1 0]	[1 2 1 3 0]
2	2	1	[0 1 1 1 0]	[1 2 1 4 5]
2	2	1	[0 1 1 1 0]	[1 2 1 6 0]
2	2	1	[0 1 1 1 0]	[1 2 1 7 5]
2	2	1	[0 1 1 1 0]	[1 2 1 9 0]
2	2	1	[0 1 1 1 0]	[1 2 3 0 0]
2	2	1	[0 1 1 1 0]	[1 2 3 1 5]
2	2	1	[0 1 1 1 

In [17]:
url2 = "D:\\Nazla_Innaya\\S2\\Kuliah\\Sem3\\Studi_Mandiri_II_FI6092\\1_5_bola\\3bola.xlsx"
names2 = ['lam_max1', 'csc_max1', 'lam_min', 'csc_min','lam_fwhm1','c_mid','lam_max2','csc_max2','lam_fwhm2','fwhm','posisi1','posisi2','posisi3','posisi4','posisi5','arah_k','arah_E','sb_putar','sudut1','sudut2','ket'] 
dataset2 = read_excel(url2, names=names2, header=None)

array2 = dataset2
print(len (array2))
X_test5 = array2.iloc[151:157,0:10].values
y_test5 = array2.iloc[151:157:,20].values
X_test6 = array2.iloc[11:17,0:10].values
y_test6 = array2.iloc[11:17:,20].values
X_test7 = array2.iloc[291:301,0:10].values
y_test7 = array2.iloc[291:301:,20].values

predictions = model.predict(X_test5)
print(predictions)
print(y_test5)

predictions = model.predict(X_test6)
print(predictions)
print(y_test6)

predictions = model.predict(X_test7)
print(predictions)
print(y_test7)


630
[2 2 2 2 2 2]
[1 1 1 1 1 1]
[2 2 2 2 1 2]
[2 2 2 2 2 2]
[2 2 2 2 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1]


## Data uji 4 bola dengan data latih tanpa 4 bola

In [18]:
url2 = "D:\\Nazla_Innaya\\S2\\Kuliah\\Sem3\\Studi_Mandiri_II_FI6092\\1_5_bola\\3bola.xlsx"
names2 = ['lam_max1', 'csc_max1', 'lam_min', 'csc_min','lam_fwhm1','c_mid','lam_max2','csc_max2','lam_fwhm2','fwhm','posisi1','posisi2','posisi3','posisi4','posisi5','arah_k','arah_E','sb_putar','sudut1','sudut2','ket'] 
dataset2 = read_excel(url2, names=names2, header=None)

array2 = dataset2
print(len (array2))
X_test8 = array2.iloc[:,0:10].values
y_test8 = array2.iloc[::,20].values

predictions = model.predict(X_test8)
print(predictions)
print(y_test8)

# Evaluate predictions using SVM
print("accurancy = ",
     accuracy_score(
         y_test8, predictions))
cf = confusion_matrix(y_test8, predictions)
print("\nconfusion matrix =\n", cf)

print("\nreport = \n", 
     classification_report(
         y_test8, predictions))

630
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2
 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 2 2 2 2
 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2
 2 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 